general:
  target_win: "Roblox"
  fov: 150
  color: 0xe400e4 # 0x2bffff 0xe400e4 0x0000fa
  debug_mode: true

aimbot:
  enabled: true
  tolerance: 75.5
  lead_factor: 0.45
  min_area: 15
  max_area: 500

offset:
  x: 3.5
  y: 1.5

sensitivity:
  smoothness: 0.75
  min_sensitivity: 3.5
  max_sensitivity: 15