general:
  target_win: "Roblox"
  fov: 200
  color: 0xe400e4 # 0x2bffff 0xe400e4 0x0000fa
  debug_mode: true

aimbot:
  enabled: true
  tolerance: 90.5
  lead_factor: 2.8 # 1.5
  min_area: 15
  max_area: 600

offset:
  x: 0
  y: 0

sensitivity:
  smoothness: 0.75 # 0.75
  min_sensitivity: 1
  max_sensitivity: 10