general:
  target_win: "Roblox"
  fov: 150
  color: 0x0000fa
  trigger_bot: false

aimbot:
  enabled: true
  tolerance: 5.5
  lead_factor: 0.12

offset:
  x: 0.0
  y: 0.0

sensitivity:
  smoothness: 0.5
  min_sensitivity: 5.0
  max_sensitivity: 15